### ISSUE TITLE
Unable to run demo with demo_data

### ISSUE THREAD

**Issue by blc49** [yxu233/Myelin#1]
I am unable to complete the demo using the demo_data. I am able to launch the GUI but each time I try to run the analysis I get the response below and an empy output file. Any help would be greatly appreciated. Thank you!

 runfile('C:/Users/Ben/Desktop/Myelin-master/CNN-UNet/main_UNet.py', wdir='C:/Users/Ben/Desktop/Myelin-master/CNN-UNet')
Parameters saved: 
Scale: 0.69 
minLength: 12
Sensitivity: 3
Rolling ball size: 0
CLAHE: 0
resize: 0

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\Users\Ben\Desktop\Myelin-master\CNN-UNet\Data_functions\UNet.py:193: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.conv2d instead.
WARNING:tensorflow:From C:\Users\Ben\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Ben\Desktop\Myelin-master\CNN-UNet\Data_functions\UNet.py:200: conv2d_transpose (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.conv2d_transpose instead.
WARNING:tensorflow:From C:\Users\Ben\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
ERROR:root:Traceback (most recent call last):
  File "C:\Users\Ben\Desktop\Myelin-master\CNN-UNet\Data_functions\test_network_UNet.py", line 50, in run_analysis
    saver.restore(sess, s_path + 'check_' + checkpoint)
  File "C:\Users\Ben\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1266, in restore
    if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
  File "C:\Users\Ben\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Ben\Anaconda3\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 372, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "C:\Users\Ben\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 361, in get_matching_files
    return get_matching_files_v2(filename)
  File "C:\Users\Ben\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 389, in get_matching_files_v2
    for single_filename in pattern
  File "C:\Users\Ben\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: ./Checkpoints/New-normalized-1024x1024 : The system cannot find the path specified.
; No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Ben/Desktop/Myelin-master/CNN-UNet/main_UNet.py", line 136, in <module>
    debug)
  File "C:\Users\Ben\Desktop\Myelin-master\CNN-UNet\Data_functions\test_network_UNet.py", line 406, in run_analysis
    raise Exception(error)
Exception: FindFirstFile failed for: ./Checkpoints/New-normalized-1024x1024 : The system cannot find the path specified.
; No such process

Error in analysis, check file order and input directory
Analysis of image 1 failed. Exiting program.

Traceback (most recent call last):

  File "<ipython-input-1-8bae26c36b52>", line 1, in <module>
    runfile('C:/Users/Ben/Desktop/Myelin-master/CNN-UNet/main_UNet.py', wdir='C:/Users/Ben/Desktop/Myelin-master/CNN-UNet')

  File "C:\Users\Ben\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\Ben\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Ben/Desktop/Myelin-master/CNN-UNet/main_UNet.py", line 147, in <module>
    post_process.read_and_comb_csv_as_SINGLES(sav_dir_folder)

  File "C:\Users\Ben\Desktop\Myelin-master\CNN-UNet\Data_functions\post_process_functions.py", line 156, in read_and_comb_csv_as_SINGLES
    output_name = all_csv[0]

IndexError: list index out of range

**Comment by yxu233** [comment]
Hello!

We appreciate your interest in our program. Apologies for the error. We have been working to generate some new and improved models for the UNet but I see now that we accidentally pushed a version that is referring to the newer models when we haven't actually uploaded them to the Github! Obviously this cannot work.

This should be fixed within the hour. You can try again then and let me know if you are having any other errors.

**Comment by yxu233** [comment]
The latest versions are now uploaded. Please let me know if the demo still does not work.

**Comment by blc49** [comment]
Just got done testing with the demo data and it's working now.

**Comment by yxu233** [comment]
Great, closing the issue. Feel free to e-mail me at yu.xu@mail.mcgill.ca if you need any other help in implementing the software.
